# Generated by Django 4.0.4 on 2022-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_certificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaciones',
            name='fecha',
            field=models.IntegerField(default=0),
        ),
    ]
